-- V1: Create products table for product-service microservice
-- Stores product catalog entries with pricing and inventory

CREATE TABLE IF NOT EXISTS products (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     BIGINT,
    name            VARCHAR(255)    NOT NULL,
    slug            VARCHAR(280)    NOT NULL UNIQUE,
    description     TEXT,
    price           DECIMAL(12, 2)  NOT NULL,
    compare_price   DECIMAL(12, 2),
    sku             VARCHAR(50)     NOT NULL UNIQUE,
    stock_quantity  INT             NOT NULL DEFAULT 0,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    image_url       VARCHAR(500),
    weight          DECIMAL(8, 2),
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug);
CREATE INDEX IF NOT EXISTS idx_products_sku ON products(sku);
CREATE INDEX IF NOT EXISTS idx_products_active ON products(is_active);
