apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "microservices-platform.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-user: {{ .Values.postgres.database.user | b64enc }}
  postgres-password: {{ .Values.postgres.database.password | b64enc }}
