apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saas-postgres-pvc
  namespace: tenant-system
  labels:
    app: saas-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
