apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: k8s-system-app
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/k8ssystem"
  SPRING_DATASOURCE_USERNAME: "appuser"
  SPRING_REDIS_HOST: "redis-service"
  SPRING_REDIS_PORT: "6379"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
