server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/content/**
          filters:
            - name: CircuitBreaker
              args:
                name: contentService
                fallbackUri: forward:/fallback/content
        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/api/recommendations/**
          filters:
            - name: CircuitBreaker
              args:
                name: recommendationService
                fallbackUri: forward:/fallback/recommendations
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/profiles/**,/api/history/**
          filters:
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/user

resilience4j:
  circuitbreaker:
    instances:
      contentService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
      recommendationService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
      userService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
