-- V1: Create orders table for trading platform
-- Stores buy/sell orders with price, quantity, and execution status

CREATE TABLE IF NOT EXISTS orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL,
    symbol          VARCHAR(10)     NOT NULL,
    side            VARCHAR(4)      NOT NULL,
    order_type      VARCHAR(20)     NOT NULL DEFAULT 'MARKET',
    status          VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    quantity        DECIMAL(18, 8)  NOT NULL,
    filled_quantity DECIMAL(18, 8)  NOT NULL DEFAULT 0,
    price           DECIMAL(18, 8),
    stop_price      DECIMAL(18, 8),
    total_amount    DECIMAL(18, 8),
    fee             DECIMAL(18, 8)  NOT NULL DEFAULT 0,
    time_in_force   VARCHAR(10)     NOT NULL DEFAULT 'GTC',
    is_cancelled    BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_symbol ON orders(symbol);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at);
