-- V2: Create portfolios table for trading platform
-- Tracks user asset holdings, cost basis, and performance metrics

CREATE TABLE IF NOT EXISTS portfolios (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL UNIQUE,
    total_value     DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    cash_balance    DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    invested_amount DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    realized_pnl    DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    unrealized_pnl  DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portfolio_holdings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id    BIGINT          NOT NULL REFERENCES portfolios(id) ON DELETE CASCADE,
    symbol          VARCHAR(10)     NOT NULL,
    quantity        DECIMAL(18, 8)  NOT NULL DEFAULT 0,
    avg_cost_basis  DECIMAL(18, 8)  NOT NULL DEFAULT 0,
    current_value   DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_portfolio_symbol UNIQUE (portfolio_id, symbol)
);

CREATE INDEX IF NOT EXISTS idx_portfolios_user ON portfolios(user_id);
CREATE INDEX IF NOT EXISTS idx_holdings_portfolio ON portfolio_holdings(portfolio_id);
CREATE INDEX IF NOT EXISTS idx_holdings_symbol ON portfolio_holdings(symbol);
