-- V3: Create trades table for trading platform
-- Records executed trades with matched orders and settlement details

CREATE TABLE IF NOT EXISTS trades (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buy_order_id    BIGINT          NOT NULL REFERENCES orders(id),
    sell_order_id   BIGINT          NOT NULL REFERENCES orders(id),
    symbol          VARCHAR(10)     NOT NULL,
    quantity        DECIMAL(18, 8)  NOT NULL,
    price           DECIMAL(18, 8)  NOT NULL,
    total_amount    DECIMAL(18, 2)  NOT NULL,
    buyer_fee       DECIMAL(18, 8)  NOT NULL DEFAULT 0,
    seller_fee      DECIMAL(18, 8)  NOT NULL DEFAULT 0,
    executed_at     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_trades_buy_order ON trades(buy_order_id);
CREATE INDEX IF NOT EXISTS idx_trades_sell_order ON trades(sell_order_id);
CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
CREATE INDEX IF NOT EXISTS idx_trades_executed ON trades(executed_at);
