apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: db-failure-postgres
spec:
  engineState: "active"
  annotationCheck: "false"
  appinfo:
    appns: "default"
    applabel: "app=postgres"
    appkind: "statefulset"
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"
            - name: CHAOS_INTERVAL
              value: "30"
            - name: FORCE
              value: "false"
---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: db-connectivity-failure
spec:
  engineState: "active"
  annotationCheck: "false"
  appinfo:
    appns: "default"
    applabel: "app=user-service"
    appkind: "deployment"
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-network-loss
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"
            - name: NETWORK_PACKET_LOSS_PERCENTAGE
              value: "100"
            - name: DESTINATION_HOSTS
              value: "postgres"
            - name: DESTINATION_PORTS
              value: "5432"
---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: db-failure-order-service
spec:
  engineState: "active"
  annotationCheck: "false"
  appinfo:
    appns: "default"
    applabel: "app=order-service"
    appkind: "deployment"
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-network-loss
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "45"
            - name: NETWORK_PACKET_LOSS_PERCENTAGE
              value: "100"
            - name: DESTINATION_HOSTS
              value: "postgres"
            - name: DESTINATION_PORTS
              value: "5432"
