server:
  port: 8082

spring:
  application:
    name: recommendation-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  recommendations:
    fallback-message: "Unable to fetch recommendations at this time"
