-- V1: Create tenants table for SaaS platform
-- Stores multi-tenant organization accounts and configuration

CREATE TABLE IF NOT EXISTS tenants (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)    NOT NULL,
    slug            VARCHAR(100)    NOT NULL UNIQUE,
    domain          VARCHAR(255),
    logo_url        VARCHAR(500),
    plan            VARCHAR(30)     NOT NULL DEFAULT 'FREE',
    status          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    max_users       INT             NOT NULL DEFAULT 10,
    max_storage_gb  INT             NOT NULL DEFAULT 5,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tenants_slug ON tenants(slug);
CREATE INDEX IF NOT EXISTS idx_tenants_plan ON tenants(plan);
CREATE INDEX IF NOT EXISTS idx_tenants_status ON tenants(status);
