-- V2: Create subscription_plans table for SaaS platform
-- Defines available subscription tiers with pricing and feature limits

CREATE TABLE IF NOT EXISTS subscription_plans (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL,
    slug            VARCHAR(120)    NOT NULL UNIQUE,
    description     TEXT,
    price_monthly   DECIMAL(10, 2)  NOT NULL DEFAULT 0,
    price_yearly    DECIMAL(10, 2)  NOT NULL DEFAULT 0,
    currency        VARCHAR(3)      NOT NULL DEFAULT 'USD',
    max_users       INT             NOT NULL DEFAULT 1,
    max_storage_gb  INT             NOT NULL DEFAULT 1,
    max_projects    INT             NOT NULL DEFAULT 1,
    features        TEXT,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tenant_subscriptions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT          NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    plan_id         BIGINT          NOT NULL REFERENCES subscription_plans(id),
    status          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    start_date      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_date        TIMESTAMP,
    auto_renew      BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tenant_subs_tenant ON tenant_subscriptions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_subs_plan ON tenant_subscriptions(plan_id);
CREATE INDEX IF NOT EXISTS idx_tenant_subs_status ON tenant_subscriptions(status);
