-- V3: Create usage_records table for SaaS platform
-- Tracks tenant resource consumption for billing and quota enforcement

CREATE TABLE IF NOT EXISTS usage_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT          NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    metric          VARCHAR(50)     NOT NULL,
    value           BIGINT          NOT NULL DEFAULT 0,
    recorded_at     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_usage_tenant ON usage_records(tenant_id);
CREATE INDEX IF NOT EXISTS idx_usage_metric ON usage_records(metric);
CREATE INDEX IF NOT EXISTS idx_usage_recorded ON usage_records(recorded_at);
