-- V1: Create orders table for order-service microservice
-- Stores order headers with customer, status, and financial data

CREATE TABLE IF NOT EXISTS orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL,
    order_number    VARCHAR(50)     NOT NULL UNIQUE,
    status          VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    subtotal        DECIMAL(12, 2)  NOT NULL,
    tax             DECIMAL(12, 2)  NOT NULL DEFAULT 0,
    shipping_cost   DECIMAL(12, 2)  NOT NULL DEFAULT 0,
    total           DECIMAL(12, 2)  NOT NULL,
    currency        VARCHAR(3)      NOT NULL DEFAULT 'USD',
    shipping_address TEXT,
    billing_address  TEXT,
    payment_method  VARCHAR(50),
    payment_status  VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    notes           TEXT,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_number ON orders(order_number);
CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at);
