-- V1: Create documents table for AI-Powered Backend
-- Stores document embeddings for RAG (Retrieval-Augmented Generation)
-- Requires pgvector extension for vector similarity search

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS documents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(255)    NOT NULL,
    content         TEXT            NOT NULL,
    content_type    VARCHAR(50)     NOT NULL DEFAULT 'TEXT',
    source          VARCHAR(255),
    author          VARCHAR(100),
    embedding       VECTOR(1536),
    token_count     INT             NOT NULL DEFAULT 0,
    chunk_index     INT             NOT NULL DEFAULT 0,
    parent_id       BIGINT          REFERENCES documents(id) ON DELETE CASCADE,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_documents_title ON documents(title);
CREATE INDEX IF NOT EXISTS idx_documents_type ON documents(content_type);
CREATE INDEX IF NOT EXISTS idx_documents_source ON documents(source);
CREATE INDEX IF NOT EXISTS idx_documents_parent ON documents(parent_id);
CREATE INDEX IF NOT EXISTS idx_documents_embedding ON documents USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
